# Generated by Django 4.0.8 on 2022-12-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shoppingcart_shoppingcartitem_shoppingcart_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
