# Generated by Django 4.0.8 on 2023-01-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shoppingcartpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCartPage',
        ),
    ]
