# Generated by Django 4.0.8 on 2023-02-06 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('shop', '0011_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenrePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('genre', models.CharField(choices=[('G', 'Girl'), ('B', 'Boys'), ('W', 'Women'), ('M', 'Men')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
