# Generated by Django 4.0.8 on 2022-11-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='size',
            name='name',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
