# Generated by Django 4.0.8 on 2022-11-25 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_brand_created_at_brand_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 25, 9, 30, 18, 867418)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
