# Generated by Django 4.0.8 on 2022-11-26 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_producttype_created_at_producttype_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 26, 8, 14, 55, 323980)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
