# Generated by Django 4.0.8 on 2022-11-26 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_subproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 26, 18, 27, 57, 253025)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
