# Generated by Django 4.0.8 on 2022-11-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_subproduct_created_at_subproduct_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproduct',
            name='SKU',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
