# Generated by Django 4.0.8 on 2022-11-26 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_subproduct_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='colour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.colour'),
        ),
    ]
