# Generated by Django 4.0.8 on 2022-11-28 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_subproduct_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.size'),
        ),
    ]
