# Generated by Django 4.0.8 on 2022-12-10 09:32

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproduct',
            name='product',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproducts', to='products.product'),
        ),
    ]
