# Generated by Django 4.0.8 on 2022-12-10 09:41

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_subproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='product',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_medias', to='products.product'),
        ),
    ]
